package main;

public enum Menu {
    ADD_NEW_STUDENT,
    ADD_NEW_TEACHER,
    ADD_NEW_ADMIN,
    REMOVE_STUDENT,
    REMOVE_ADMIN,
    REMOVE_TEACHER,
    ADD_MATH_COURSE,
    ADD_PROGRAMMING_COURSE,
    CREATE_QUIZ,
    PRINT_USERS,
    PRINT_CHEAPEST_COURSES,
    PRINT_QUIZZ,
    SET_QUIZ_PROGRAMMING,
    SET_QUIZ_MATH,
    ENROLL_STUDENT,
    DISENROLL_STUDENT,
    PRINT_COURSES,
    PRINT_STUDENT_COURSES,
    UPDATE_TEACHER,
    EXIT
}
